[project]
name = "swipe-decoder-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "pydantic>=2.11.7",
    "torch>=2.7.1",
    "transformers>=4.53.1",
    "uvicorn>=0.35.0",
]

[project.optional-dependencies]
build = ["setuptools", "cython"]

[tool.setuptools]
py-modules = ['decoder']

[dependency-groups]
dev = [
    "fastapi[standard]>=0.116.1",
    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "tqdm>=4.67.1",
]
